<?php

use Illuminate\Database\Eloquent\Model as Eloquent;

class DaftarDplk extends Eloquent {
    protected $table = 'daftar';
    protected $fillable = [
        'jenis',
        'firstName',
        'tempat',
        'tanggal',
        'bulan',
        'tahun',
        'agama',
        'jen_kel',
        'status',
        'nik',
        'alamat',
        'RT',
        'RW',
        'zip',
        'kelurahan',
        'kecamatan',
        'kota',
        'provinsi',
        'email',
        'noHp',
        'nonpwp',
        'negaraan',
        'pekerjaan',
        'gaji',
        'pendapatan_lain',
        'investasi',
        'usia_pensiun',
        'iuran_kerja',
        'iuran_peserta',
        'firstName2',
        'tempat_lahir',
        'tanggal_lahir',
        'bulan_lahir',
        'tahun_lahir',
        'alamat_w',
        'kecamatan_w',
        'kota_w',
        'zip_w',
        'tlp_rmh',
        'nomerhp_w',
        'hub_peserta',
        'kerabat',
        'noKerabat',
        'ktr_Nama',
        'jabatan',
        'alm_ktr',
        'kec_ktr',
        'tel_kantor',
        'nama_lengkap',
        'l_tempat',
        'lahir_tanggal',
        'lahir_bulan',
        'lahir_tahun',
        'no_Induk',
        'no_alamat',
        'no_kec',
        'no_kota',
        'no_zip',
        'telp_No',
        'kerja',
        'kantor_nama',
        'jenis_usaha',
        'jabat',
        'penghasilan',
        'no_rek',
        'nama_rek',
        'tgl_debet',
        'nominal_debet'
    ];

    public $timestamps = false;
}